Update with RTEMS 6 and Gitlab changes

diff --git a/rtems-release b/rtems-release
--- a/rtems-release
+++ b/rtems-release
@@ -60,6 +60,18 @@ usage() {
 }
 
 #
+# Check for commands
+#
+set +e
+ > /dev/null
+has_pandoc=$?
+if [ "command -v pandoc"no = no ]; then
+ echo "error: no pandoc installed"
+ exit 1
+fi
+set -e
+
+#
 # Option defaults
 #
 release_url=${rtems_release_url}
@@ -126,32 +138,44 @@ if [ -e ${release} ]; then
 fi
 
 #
+# Package paths
+#
+pkg_rtems_source_builder=rtems/tools/rtems-source-builder
+pkg_rtems_deployment=rtems/tools/rtems-deployment
+pkg_rtems_tools=rtems/tools/rtems-tools
+pkg_rtems=rtems/rtos/rtems
+pkg_rtems_libbsd=rtems/pkg/rtems-libbsd
+pkg_rtems_net_legacy=rtems/pkg/rtems-net-legacy
+pkg_rtems_net_services=rtems/pkg/rtems-net-services
+pkg_rtems_examples=rtems/rtos/rtems-examples
+pkg_rtems_docs=rtems/docs/rtems-docs
+
+#
 # Package the RSB, must be before the kernel. The kernel worker script uses the
 # RSB to create autoconf and automake so it can bootstrap the kernel.
 #
-build rtems-source-builder ${version} ${revision} ${release_url}
-build rtems-tools          ${version} ${revision} ${release_url}
-build rtems                ${version} ${revision} ${release_url} rtems-release-kernel
+build ${pkg_rtems_source_builder} ${version} ${revision} ${release_url}
+build ${pkg_rtems_tools}          ${version} ${revision} ${release_url}
+build ${pkg_rtems}                ${version} ${revision} ${release_url} rtems-release-kernel
 if [ ${rtems_libbsd} = yes ]; then
- build rtems-libbsd ${version} ${revision} ${release_url}
+ build ${pkg_rtems_libbsd} ${version} ${revision} ${release_url}
 fi
-build rtems-source-builder ${version} ${revision} ${release_url} rtems-release-rsb-version
+if [ ${rtems_net_legacy} = yes ]; then
+ build ${pkg_rtems_libbsd} ${version} ${revision} ${release_url}
+fi
+build ${pkg_rtems_source_builder} ${version} ${revision} ${release_url} rtems-release-rsb-version
+if [ ${rtems_deployment} = yes ]; then
+ build ${pkg_rtems_deployment} ${version} ${revision} ${release_url}
+fi
 if [ ${rtems_examples} = yes ]; then
- if [ ${version} -lt 5 ]; then
-  build examples-v2 ${version} ${revision} ${release_url}
-  # Hack around the repo naming.
-  mv ${release}/examples-v2-${release}.tar.${comp_ext} \
-     ${release}/rtems-examples-v2-${release}.tar.${comp_ext}
- else
-  build rtems-examples ${version} ${revision} ${release_url}
- fi
+ build ${pkg_rtems_examples} ${version} ${revision} ${release_url}
 fi
 
 #
 # Documentation.
 #
 if [ ${rtems_docs} = yes ]; then
- ./rtems-release-docs rtems-docs ${version} ${revision} ${release_url}
+ ./rtems-release-docs ${pkg_rtems_docs} ${version} ${revision} ${release_url}
 fi
 
 #
@@ -182,7 +206,7 @@ echo "] Create the release information"
 #
 # Copy these release scripts to a contrib directory.
 #
-for f in README.txt \
+for f in README.md \
 	 ${rtems_readme} \
 	 rtems-mailer \
          rtems-release \
diff --git a/rtems-release-kernel b/rtems-release-kernel
--- a/rtems-release-kernel
+++ b/rtems-release-kernel
@@ -44,8 +44,8 @@ set -e
 # The package, version, revision and release URL.
 #
 if [ $# -ne 5 ]; then
-    echo "error: must be arguments, the package, version," \
-	 "release, release URL and the top directory."
+ echo "error: must be arguments, the package, version," \
+      "release, release URL and the top directory."
  exit 1
 fi
 package=$1
@@ -106,16 +106,9 @@ cd ${prefix}
   # Waf build system. Update RTEMS version and collect the BSPs
   #
   echo "] RTEMS Build System: waf"
-  f="spec/build/cpukit/optvermaj.yml"
-  echo "] Update ${f}"
-  sed -i "s/- get-string-command-line:.*/- get-string-command-line: '${version}'/" ${f}
-  f="spec/build/cpukit/optvermin.yml"
-  echo "] Update ${f}"
-  minor=$(echo ${revision} | sed 's/-.*//')
-  sed -i "s/- set-value:.*/- set-value: '${minor}'/" ${f}
-  f="spec/build/cpukit/optverrev.yml"
-  echo "] Update ${f}"
-  sed -i "s/- set-value:.*/- set-value: '0'/" ${f}
+  f="VERSION"
+  echo "] Creating ${f}: ${release}"
+  echo -e "[RTEMS_VERSION]\nRTEMS_VERSION_CONTROL_KEY = ${release}" > ${f}
  else
   #
   # Autoconf build system. Bootstrap RTEMS
@@ -150,10 +143,10 @@ EOF
  echo "] Generate ARCH-BSP.txt"
  ./rtems-bsps -m > ${toptop}/ARCH-BSP.md
  echo "] Generate README"
- cp README README.tmp
+ pandoc README.md -t plain -o README.tmp
  cat README.tmp | \
-  sed -e "s|docs\.rtems\.org\/branches\/master\/|docs\.rtems\.org\/releases\/rtems-docs-${release}\/|g" | \
-  sed -e "s|docs\.rtems\.org\/doxygen\/branches\/master\/|docs\.rtems\.org\/doxygen\/releases\/rtems-doxygen-${release}\/|g" | \
+  sed -e "s|docs\.rtems\.org\/branches\/main\/|docs\.rtems\.org\/releases\/rtems-docs-${release}\/|g" | \
+  sed -e "s|docs\.rtems\.org\/doxygen\/branches\/main\/|docs\.rtems\.org\/doxygen\/releases\/rtems-doxygen-${release}\/|g" | \
   awk "/https:\/\/git\.rtems\.org\/rtems/{\$0=\$0\"?h=${version}\"}{print}" > README
  rm -r README.tmp
  cd ..
@@ -168,12 +161,14 @@ if [ ${rtems_autoconf} = yes ]; then
 fi
 
 #
-# Only build doxygen output if present on the system.
+# Build doxygen output and error command is not present.
 #
+set -e
 if [ "`command -v doxygen`"no = no ]; then
- echo "warning: doxygen not built: doxygen not found"
- exit 0
+ echo "error: doxygen not built: doxygen not found"
+ exit 1
 fi
+set +e
 
 #
 # Doxygen
